version: '3.8'

services:
  jekyll:
    image: github_portfolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    command: bundle exec jekyll serve --watch --incremental --force_polling --livereload --host 0.0.0.0
